---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: acjimeneza/ms-chart:a1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12}}
            {{- else }}
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100"
            {{- end}}
          {{- if .Values.environmentVar }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-conf
                optional: true
          {{- end}}
          

