apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf
  labels:
    name: {{ .Release.Name }}-conf
    generator: helm
    date: {{ now | htmlDate }}
{{/* {{- template "example.labels" . }}
*/}}
data:
  testvalue: {{ .Values.testvalue | quote}}
  {{- with .Values.favorite }}
  drink: {{  .drink | default "tea" | quote}}
  food: {{ .food | upper | quote }}
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
