---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deploy
  labels:
    app: name-app
spec:
  selector:
    matchLabels:
      app: name-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: name-app
    spec:
      containers:
        - name: name-app
          image: acjimeneza/ms-chart:a1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
