apiVersion: v1
kind: Service
metadata:
  name: name-service
  labels:
    app: name-app
spec:
  type: LoadBalancer
  selector:
    app: name-app
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 5000
